In [1]:
#IMPORTS:
import pandas as pd
import scipy as sc
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import matplotlib.colors as mcolors
from sklearn import preprocessing
from math import sqrt
from sklearn.metrics import r2_score

#model Metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split

#classifiers
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [3]:
#stored datasets
%store -r fin_vars7
%store -r scaled_feat_fin_vars

In [5]:
scaled_feat_fin_vars.head()

LIMIT_BAL    SEP_P0    AUG_P2    JUL_P3    JUN_P4    MAY_P5    APR_P6  \
0  -1.122109  1.918712  1.878707 -0.716332 -0.687567 -1.606841 -1.541377   
1  -0.276941 -0.910476  1.878707  0.163404  0.226659  0.280378  2.133879   
2  -0.530492  0.032587  0.129175  0.163404  0.226659  0.280378  0.296251   
3  -0.868559  0.032587  0.129175  0.163404  0.226659  0.280378  0.296251   
4  -0.868559 -0.910476  0.129175 -0.716332  0.226659  0.280378  0.296251   

   BILLAMT_SEP  BILLAMT_AUG  BILLAMT_JUL  ...  BILLAMT_MAY  BILLAMT_APR  \
0    -0.727493    -0.731803    -0.771106  ...    -0.748119    -0.730187   
1    -0.751432    -0.759664    -0.728867  ...    -0.665617    -0.651115   
2    -0.234986    -0.510756    -0.498340  ...    -0.391178    -0.353155   
3     0.110213     0.181339     0.258964  ...    -0.056612    -0.013731   
4    -0.636016    -0.679844    -0.026223  ...    -0.290935    -0.266298   

   PAYAMT_SEP  PAYAMT_AUG  PAYAMT_JUL  PAYAMT_JUN  PAYAMT_MAY  PAYAMT_JUN  \
0   -0.654247   -0.480326   -0.569704   -0.553255   -0.553255   -0.571994   
1   -0.654247   -0.432751   -0.400531   -0.371094   -0.371094   -0.571994   
2   -0.392126   -0.356264   -0.400531   -0.371094   -0.371094   -0.380295   
3   -0.308897   -0.276871   -0.366696   -0.352878   -0.352878   -0.367068   
4   -0.308897    5.025490    1.122027    1.086189    1.086189   -0.439913   

   PAYAMT_MAY  PAYAMT_APR  
0   -0.571994   -0.526674  
1   -0.571994   -0.179752  
2   -0.380295    0.340631  
3   -0.367068   -0.353213  
4   -0.439913   -0.408894  

[5 rows x 21 columns]

In [9]:
scaled_int = scaled_feat_fin_vars.copy()
scaled_int = scaled_int.astype("int")

In [10]:
fin_features = scaled_feat_fin_vars.iloc[:,0:21]
print('Summary of Financial feature sample')
fin_features.info()

Summary of Financial feature sample
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26133 entries, 0 to 29999
Data columns (total 21 columns):
LIMIT_BAL      26133 non-null float64
SEP_P0         26133 non-null float64
AUG_P2         26133 non-null float64
JUL_P3         26133 non-null float64
JUN_P4         26133 non-null float64
MAY_P5         26133 non-null float64
APR_P6         26133 non-null float64
BILLAMT_SEP    26133 non-null float64
BILLAMT_AUG    26133 non-null float64
BILLAMT_JUL    26133 non-null float64
BILLAMT_JUN    26133 non-null float64
BILLAMT_MAY    26133 non-null float64
BILLAMT_APR    26133 non-null float64
PAYAMT_SEP     26133 non-null float64
PAYAMT_AUG     26133 non-null float64
PAYAMT_JUL     26133 non-null float64
PAYAMT_JUN     26133 non-null float64
PAYAMT_MAY     26133 non-null float64
PAYAMT_JUN     26133 non-null float64
PAYAMT_MAY     26133 non-null float64
PAYAMT_APR     26133 non-null float64
dtypes: float64(21)
memory usage: 4.4 MB


In [11]:
#dependent var
fin_DV= fin_vars7['DEFAULT']
print(fin_DV)

0        1
1        1
2        0
3        0
4        0
        ..
29992    0
29994    1
29995    0
29996    0
29999    1
Name: DEFAULT, Length: 26133, dtype: int32


In [12]:
#setup training set
x_fin_train = (fin_features[:18293])
#70% of 26,133 obs
x_fin_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18293 entries, 0 to 20864
Data columns (total 21 columns):
LIMIT_BAL      18293 non-null float64
SEP_P0         18293 non-null float64
AUG_P2         18293 non-null float64
JUL_P3         18293 non-null float64
JUN_P4         18293 non-null float64
MAY_P5         18293 non-null float64
APR_P6         18293 non-null float64
BILLAMT_SEP    18293 non-null float64
BILLAMT_AUG    18293 non-null float64
BILLAMT_JUL    18293 non-null float64
BILLAMT_JUN    18293 non-null float64
BILLAMT_MAY    18293 non-null float64
BILLAMT_APR    18293 non-null float64
PAYAMT_SEP     18293 non-null float64
PAYAMT_AUG     18293 non-null float64
PAYAMT_JUL     18293 non-null float64
PAYAMT_JUN     18293 non-null float64
PAYAMT_MAY     18293 non-null float64
PAYAMT_JUN     18293 non-null float64
PAYAMT_MAY     18293 non-null float64
PAYAMT_APR     18293 non-null float64
dtypes: float64(21)
memory usage: 3.1 MB


In [13]:
#dependent var training set
y_fin_train = fin_DV[:18293]
y_fin_train_count = len(y_fin_train.index)
print('The number of observations in the Y training set is:', str(y_fin_train_count))
y_fin_train.head()

The number of observations in the Y training set is: 18293


0    1
1    1
2    0
3    0
4    0
Name: DEFAULT, dtype: int32

In [14]:
#testing set
x_fin_test = fin_features[-7840:]
x_fin_test_count = len(x_fin_test.index)
print('The number of observations in the feature testing set is:',str(x_fin_test_count))
print(x_fin_test.head())

The number of observations in the feature testing set is: 7840
       LIMIT_BAL    SEP_P0    AUG_P2    JUL_P3    JUN_P4    MAY_P5    APR_P6  \
20865  -1.122109 -0.910476 -0.745591  0.163404  0.226659  0.280378  0.296251   
20866  -0.784042  0.975650  1.878707  1.922875  2.055111  2.167598  2.133879   
20867   0.145643  0.975650  1.878707  1.922875  2.055111  2.167598  0.296251   
20868  -0.868559  0.975650  1.878707  0.163404  0.226659  2.167598  0.296251   
20869   0.737260  0.032587  0.129175  0.163404  0.226659  0.280378  0.296251   

       BILLAMT_SEP  BILLAMT_AUG  BILLAMT_JUL  ...  BILLAMT_MAY  BILLAMT_APR  \
20865    -0.779066    -0.555026    -0.582035  ...    -0.494669    -0.477208   
20866     0.128065     0.213509     0.247646  ...     0.516505     0.530347   
20867    -0.455103    -0.405503    -0.390611  ...    -0.284344    -0.641828   
20868    -0.112141    -0.092780    -0.020161  ...     0.145332     0.203435   
20869     3.673705     3.745263     4.103023  ...     3.77904

In [15]:
y_fin_test = fin_DV[-7840:]
y_fin_test_count = len(y_fin_test.index)
print('The number of observations in the Y testing set is:', str(y_fin_test_count))
y_fin_test.head()

The number of observations in the Y testing set is: 7840


20865    0
20866    0
20867    0
20868    0
20869    0
Name: DEFAULT, dtype: int32

In [16]:
x_fin_train, x_fin_test, y_fin_train, y_fin_test = train_test_split(x_fin_train, y_fin_train)

In [17]:
x_fin_train.shape, x_fin_test.shape

((13719, 21), (4574, 21))

In [18]:
x_fin_train, x_fin_test, y_fin_train, y_fin_test = train_test_split(x_fin_train, y_fin_train)
x_fin_train.shape, x_fin_test.shape

((10289, 21), (3430, 21))

In [19]:
#tuning parameters and model definition
#out of the box tries
fin_modelDTC = DecisionTreeClassifier()
fin_modelLR = LogisticRegression()
fin_modelKN = KNeighborsClassifier()

In [20]:
fin_modelKN.fit(x_fin_train, y_fin_train)
fin_modelDTC.fit(x_fin_train, y_fin_train)
fin_modelLR.fit(x_fin_train, y_fin_train)

C:\Users\Samantha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
print(cross_val_score(fin_modelKN, x_fin_train, y_fin_train))
fin_modelKN.score(x_fin_train, y_fin_train)

C:\Users\Samantha\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


[0.78571429 0.78396501 0.77806941]


0.8371075906307708

In [22]:
print(cross_val_score(fin_modelDTC, x_fin_train, y_fin_train))
fin_modelDTC.score(x_fin_train, y_fin_train)

C:\Users\Samantha\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


[0.71982507 0.71020408 0.70312044]


0.9928078530469433

In [23]:
print(cross_val_score(fin_modelLR, x_fin_train, y_fin_train))
fin_modelLR.score(x_fin_train, y_fin_train)

C:\Users\Samantha\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Samantha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Samantha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Samantha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[0.803207   0.80262391 0.80373287]


0.8039653999416853

In [24]:
predictions_fin = fin_modelDTC.predict(x_fin_test)
rmse_fin = sqrt(mean_squared_error(y_fin_test, predictions_fin))
predRsquared_fin = r2_score(y_fin_test, predictions_fin)
print('R Squared: %.3f' % predRsquared_fin)
print('RMSE: %.3f' %rmse_fin)

R Squared: -0.610
RMSE: 0.534


In [25]:
predictions_finLR = fin_modelLR.predict(x_fin_test)
rmse_finLR = sqrt(mean_squared_error(y_fin_test, predictions_finLR))
predRsquared_finLR = r2_score(y_fin_test, predictions_finLR)
print('R Squared: %.3f' % predRsquared_finLR)
print('RMSE: %.3f' %rmse_finLR)

R Squared: -0.147
RMSE: 0.450


In [26]:
#should not be using R2 for classification metrics
#importing the metrics package from sklearn lib
from sklearn import metrics

cm = metrics.confusion_matrix(y_fin_test, predictions_finLR)
cm_df = pd.DataFrame(cm,
                    columns = ['Predicted Negative', 'Predicted Positive'],
                    index = ['Actual Negative', 'Actual Positive'])
cm_df

Predicted Negative  Predicted Positive
Actual Negative                2535                 107
Actual Positive                 589                 199

In [28]:
cmDTC= metrics.confusion_matrix(y_fin_test, predictions_fin)
cm_dfDTC= pd.DataFrame(cmDTC,
                    columns = ['Predicted Negative', 'Predicted Positive'],
                    index = ['Actual Negative', 'Actual Positive'])
cm_dfDTC

Predicted Negative  Predicted Positive
Actual Negative                2135                 507
Actual Positive                 470                 318

In [58]:
#creating a function to report confusion matrics
#save confusion matrix and slice into 4 pieces
def confusion_metrics (conf_matrix):
   TP = conf_matrix[1][1]
   TN = conf_matrix[0][0]
   FP = conf_matrix[0][1]
   FN = conf_matrix[1][0]

   print('True Positives:', TP)
   print('True Negatives:', TN)
   print('False Positives:', FP)
   print('False Negatives:', FN)

#calculate accuracy
   conf_accuracy = (float (TP+TN) /float(TP + TN + FP + FN))

#calculate mis-classifcation
   conf_misclassification = 1 - conf_accuracy

#calculate the sensitivity
   conf_sensitivity = (TP /float(TP + FN))

#calculate the specificity
   conf_specificity = (TN/float(TN + FP))

#calculate precision
   conf_precision = (TN/ float(TN + FP))

   print('-'*50)
   print(f'Accuracy: {round(conf_accuracy,2)}')
   print(f'Mis-Classification: {round(conf_misclassification,2)}')
   print(f'Sensitivity: {round(conf_sensitivty,2)}')
   print(f'Specificity: {round(conf_specificity,2)}')
   print(f'Precision: {round(conf_precision,2)}')

In [62]:
#creating a function to report confusion matrics
#save confusion matrix and slice into 4 pieces
def confusion_metrics (cm_df):
   TP = cm_df[1][1]
   TN = cm_df[0][0]
   FP = cm_df[0][1]
   FN = cm_df[1][0]

   print('True Positives:', TP)
   print('True Negatives:', TN)
   print('False Positives:', FP)
   print('False Negatives:', FN)

#calculate accuracy
   conf_accuracy = (float (TP+TN) /float(TP + TN + FP + FN))

#calculate mis-classifcation
   conf_misclassification = 1 - conf_accuracy

#calculate the sensitivity
   conf_sensitivity = (TP /float(TP + FN))

#calculate the specificity
   conf_specificity = (TN/float(TN + FP))

#calculate precision
   conf_precision = (TN/ float(TN + FP))

   print('-'*50)
   print(f'Accuracy: {round(conf_accuracy,2)}')
   print(f'Mis-Classification: {round(conf_misclassification,2)}')
   print(f'Sensitivity: {round(conf_sensitivty,2)}')
   print(f'Specificity: {round(conf_specificity,2)}')
   print(f'Precision: {round(conf_precision,2)}')

In [63]:
#accuracy metrics for DTC predictions
print(metrics.accuracy_score(y_fin_test, predictions_fin))

0.7151603498542274


In [64]:
#accuracy metrics for DLR predictions
print(metrics.accuracy_score(y_fin_test, predictions_finLR))

0.7970845481049562
